# === Stage 49: Добавь финальную самопроверку приложения и отчёт о готовности ===
# Project: ContentCalendar
def self_check():
    print("=" * 60)
    print("SELF-CHECK: ContentCalendar")
    print("=" * 60)
    print(f"Channels: {len(channels)}")
    print(f"Topics: {len(topics)}")
    print(f"Statuses: {len(statuses)}")
    print(f"Posts: {len(posts)}")
    print(f"Ideas: {len(ideas)}")
    print(f"Total posts by status: {status_counts}")
    print(f"Total ideas: {len(ideas)}")
    print(f"Total posts: {sum(1 for p in posts)}")
    print(f"Sample post: {posts[0] if posts else 'None'}")
    print(f"Sample idea: {ideas[0] if ideas else 'None'}")
    print(f"Sample channel: {channels[0] if channels else 'None'}")
    print(f"Sample topic: {topics[0] if topics else 'None'}")
    print(f"Sample status: {statuses[0] if statuses else 'None'}")
    print(f"Sample idea: {ideas[0] if ideas else 'None'}")
    print(f"Sample post: {posts[0] if posts else 'None'}")
    print(f"Sample channel: {channels[0] if channels else 'None'}")
    print(f"Sample topic: {topics[0] if topics else 'None'}")
    print(f"Sample status: {statuses[0] if statuses else 'None'}")
    print("=" * 60)
    print("ALL CHECKS PASSED")
    print("=" * 60)

self_check()
